name: 'cleanup'
description: 'Cleanup resources on failure'
inputs:
  project_name:
    description: 'Name of the service'
    required: true
  runtime_mode:
    description: 'Deployment runtime mode'
    required: true
  github_app_token:
    description: 'GitHub token'
    required: false
  environments:
    description: 'JSON array of environments'
    required: true
  workspace_id:
    description: 'Postman Workspace ID'
    required: false
  ecs_service_name:
    description: 'ECS Service Name'
    required: false
  ecs_target_group_arn:
    description: 'ECS Target Group ARN'
    required: false
  ecs_listener_rule_arn:
    description: 'ECS Listener Rule ARN'
    required: false
  postman_api_key:
    description: 'Postman API Key'
    required: true
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: false
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: false
  aws_region:
    description: 'AWS Region'
    required: true
    default: 'eu-central-1'
runs:
  using: 'node20'
  main: 'dist/index.js'
