name = "vzw-partner-portal"
account_id = "c99ca0b9ebff4418013b938ff6262abc"
compatibility_date = "2026-03-26"
main = "src/worker.ts"

[assets]
directory = "./public/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
INTERNAL_CATALOG_ORIGIN = "https://vzw.pm-demo.dev"
CF_ACCESS_CLIENT_ID = "278fe44e61443629d3a8c1189134b7ac.access"

[[routes]]
pattern = "partner.vzw.pm-demo.dev"
custom_domain = true
